# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.7'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'typhoeus', '~> 1.4'
gem 'rack-cors', '~> 2.0'
gem 'json', '~> 2.7'
gem 'pry'

group :development do
  gem 'rerun', '~> 0.14'
end
